import { Textarea } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { DefaultLayout } from '../layouts/DefaultLayout'

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <Head>
        <title>SML Memo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Textarea placeholder="Here is a sample placeholder" />
      </main>
    </DefaultLayout>
  )
}

export default Home
